In [2]:
import pandas as pd
import re

In [3]:
# Load all_articles.csv into a DataFrame
df = pd.read_csv('data/00_raw/all_articles.csv')
df

,title,summary,section,keywords,published_date,url
0,"Paid Notice: Deaths BAUER, LILLIAN","BAUER-Lillian. December 30, 1999. Beloved wife...",Archives,"['Bauer, Lillian']",2000-01-01 05:00:00+00:00,https://www.nytimes.com/2000/01/01/classified/...
1,"Paid Notice: Deaths GLUCK, SAMUEL E.","GLUCK-Samuel E.. At age 74. On December 31, 19...",Archives,"['GLUCK, SAMUEL E.']",2000-01-01 05:00:00+00:00,https://www.nytimes.com/2000/01/01/classified/...
2,Folds of Newspapers Yield Symbols of Peace,"Joshua Davis, high school student from Montcla...",New York,"['Montclair (NJ)', 'DAVIS, JOSHUA', 'Newspaper...",2000-01-01 05:00:00+00:00,https://www.nytimes.com/2000/01/01/nyregion/fo...
3,"T. F. Lambert Jr., 85, Lawyer at Nuremberg","Thomas Francis Lambert Jr, law professor and d...",U.S.,"['Lambert, Thomas Francis Jr', 'Biographical I...",2000-01-01 05:00:00+00:00,https://www.nytimes.com/2000/01/01/us/t-f-lamb...
4,"Paid Notice: Deaths SMITH, KATHERINE ANNE","SMITH-Katherine Anne. Died on December 30, 199...",Archives,"['Smith, Katherine Anne']",2000-01-01 05:00:00+00:00,https://www.nytimes.com/2000/01/01/classified/...
...,...,...,...,...,...,...
299604,Environmental groups demand EPA to start monit...,A new legal petition filed by more than 170 to...,Environment,"['US Environmental Protection Agency', 'Plasti...",2024-12-01 13:00:07+00:00,https://www.theguardian.com/environment/2024/d...
299605,"Land degradation expanding by 1m sq km a year,...",Land degradation is expanding worldwide at the...,Environment,"['Desertification', 'Farming', 'Deforestation'...",2024-12-01 12:00:07+00:00,https://www.theguardian.com/environment/2024/d...
299606,"‘If I’m sent to Japan, I’m not coming home’: j...",The humpback whales watched by Paul Watson fro...,Environment,"['Sea Shepherd Conservation Society', 'Whales'...",2024-12-01 08:00:01+00:00,https://www.theguardian.com/environment/2024/d...
299607,Cheaper loans on table to urge UK motorists to...,There is “no route to net zero” that ignores t...,Environment,"['Electric, hybrid and low-emission cars', 'Au...",2024-12-01 07:00:50+00:00,https://www.theguardian.com/environment/2024/d...
299608,People are angry about the floods – but turnin...,There is an irony to the fact that many Welsh ...,Environment,"['Climate crisis', 'Flooding', 'Extreme weathe...",2024-12-01 06:00:48+00:00,https://www.theguardian.com/environment/2024/d...

## Filter sections

In [4]:
# Check all sections, remove nan, sort them, and print them out
sections = df['section'].dropna().unique()
sections.sort()
sections

array(['Admin', 'Archives', 'Arts', 'At Home', 'Automobiles', 'Blogs',
       'Book Review', 'Books', 'Booming', 'Briefing', 'Burst',
       'Business Day', 'Climate', 'Corrections', 'Crosswords & Games',
       'Education', 'Environment', 'Fashion & Style', 'Food',
       'Great Homes & Destinations', 'Headway', 'Health', 'Home & Garden',
       'International Home', 'Job Market', 'Lens', 'Magazine', 'Movies',
       'Multimedia/Photos', 'New York', 'Obituaries', 'Opinion',
       'Parenting', 'Real Estate', 'Science', 'Smarter Living',
       'Special Series', 'Sports', 'Style', 'T Magazine', 'Technology',
       'The New York Times Presents', 'The Upshot', 'Theater',
       'Times Insider', 'Today’s Paper', 'Travel', 'U.S.', 'Universal',
       'Washington', 'Watching', 'Well', 'World', 'Your Money'],
      dtype=object)

In [5]:
# Analyze section distribution
section_counts = df['section'].value_counts(dropna=False)
print("=== Section Distribution ===")
print(section_counts)
print(f"\nTotal sections: {len(sections)}")
print(f"Articles with no section: {df['section'].isna().sum()}")

=== Section Distribution ===
section
New York                       69610
Business Day                   56914
Environment                    55215
Sports                         31692
Archives                       24922
Books                          20381
Technology                     11990
Arts                            8410
U.S.                            4376
World                           2852
Your Money                      2775
Obituaries                      1895
Real Estate                     1422
Job Market                      1098
The Upshot                       838
Theater                          822
Health                           816
Movies                           677
Automobiles                      371
Science                          363
Education                        353
Travel                           298
Style                            292
Fashion & Style                  279
Climate                          253
Smarter Living                   203
Crosswords & Games               152
Food                             133
Multimedia/Photos                 61
Washington                        40
Well                              23
Blogs                             12
Lens                              11
Corrections                       11
Booming                            6
Briefing                           6
Parenting                          5
Opinion                            4
Magazine                           4
Universal                          4
Great Homes & Destinations         3
Burst                              2
Times Insider                      2
Book Review                        2
Home & Garden                      1
NaN                                1
Today’s Paper                      1
At Home                            1
Watching                           1
International Home                 1
Admin                              1
Special Series                     1
Headway                            1
The New York Times Presents        1
T Magazine                         1
Name: count, dtype: int64

Total sections: 54
Articles with no section: 1

In [6]:
# Define sections to INCLUDE (business-relevant for company mentions)
INCLUDE_SECTIONS = [
    # Core Business
    'Business Day',
    'Your Money',
    'Job Market',
    
    # Relevant companies possible, have to use entity linking to filter out non-company mentions
    'Technology',
    'Automobiles',
    'Environment', 
    'Climate',
    'Health', 
    'Real Estate',
    'Science',  
    'Smarter Living', # discusses consumer products and lifestyle, which may include company mentions

    
    # News sections 
    'U.S.',
    'World',
    'New York',
    'Washington',
    'The Upshot'
    
    
]

# Analyze which sections we're including
print("=== SECTIONS TO INCLUDE ===")
section_counts = df['section'].value_counts(dropna=False)

for section in INCLUDE_SECTIONS:
    if section in section_counts.index:
        count = section_counts[section]
        pct = count / len(df) * 100
        print(f"- {section}: {count} articles ({pct:.2f}%)")
    else:
        print(f"- {section}: NOT FOUND in data")

total_to_keep = df[df['section'].isin(INCLUDE_SECTIONS)].shape[0]
print(f"\nTotal articles to include: {total_to_keep} ({total_to_keep/len(df)*100:.2f}%)")

=== SECTIONS TO INCLUDE ===
- Business Day: 56914 articles (19.00%)
- Your Money: 2775 articles (0.93%)
- Job Market: 1098 articles (0.37%)
- Technology: 11990 articles (4.00%)
- Automobiles: 371 articles (0.12%)
- Environment: 55215 articles (18.43%)
- Climate: 253 articles (0.08%)
- Health: 816 articles (0.27%)
- Real Estate: 1422 articles (0.47%)
- Science: 363 articles (0.12%)
- Smarter Living: 203 articles (0.07%)
- U.S.: 4376 articles (1.46%)
- World: 2852 articles (0.95%)
- New York: 69610 articles (23.23%)
- Washington: 40 articles (0.01%)
- The Upshot: 838 articles (0.28%)

Total articles to include: 209136 (69.80%)

In [7]:
# Sections we're EXCLUDING 
exclude_sections = [s for s in section_counts.index if s not in INCLUDE_SECTIONS and pd.notna(s)]

print("\n=== SECTIONS TO EXCLUDE (not in include list) ===")
for section in sorted(exclude_sections):
    count = section_counts[section]
    pct = count / len(df) * 100
    print(f"- {section}: {count} articles ({pct:.2f}%)")

total_to_exclude = df[df['section'].isin(exclude_sections)].shape[0]
print(f"\nTotal articles to exclude: {total_to_exclude} ({total_to_exclude/len(df)*100:.2f}%)")

=== SECTIONS TO EXCLUDE (not in include list) ===
- Admin: 1 articles (0.00%)
- Archives: 24922 articles (8.32%)
- Arts: 8410 articles (2.81%)
- At Home: 1 articles (0.00%)
- Blogs: 12 articles (0.00%)
- Book Review: 2 articles (0.00%)
- Books: 20381 articles (6.80%)
- Booming: 6 articles (0.00%)
- Briefing: 6 articles (0.00%)
- Burst: 2 articles (0.00%)
- Corrections: 11 articles (0.00%)
- Crosswords & Games: 152 articles (0.05%)
- Education: 353 articles (0.12%)
- Fashion & Style: 279 articles (0.09%)
- Food: 133 articles (0.04%)
- Great Homes & Destinations: 3 articles (0.00%)
- Headway: 1 articles (0.00%)
- Home & Garden: 1 articles (0.00%)
- International Home: 1 articles (0.00%)
- Lens: 11 articles (0.00%)
- Magazine: 4 articles (0.00%)
- Movies: 677 articles (0.23%)
- Multimedia/Photos: 61 articles (0.02%)
- Obituaries: 1895 articles (0.63%)
- Opinion: 4 articles (0.00%)
- Parenting: 5 articles (0.00%)
- Special Series: 1 articles (0.00%)
- Sports: 31692 articles (10.58%)
- Style: 292 articles (0.10%)
- T Magazine: 1 articles (0.00%)
- The New York Times Presents: 1 articles (0.00%)
- Theater: 822 articles (0.27%)
- Times Insider: 2 articles (0.00%)
- Today’s Paper: 1 articles (0.00%)
- Travel: 298 articles (0.10%)
- Universal: 4 articles (0.00%)
- Watching: 1 articles (0.00%)
- Well: 23 articles (0.01%)

Total articles to exclude: 90472 (30.20%)

In [8]:
# Apply section filtering (include only relevant sections AND exclude NaN)
df_filtered = df[
    (df['section'].isin(INCLUDE_SECTIONS)) & 
    (df['section'].notna())
].copy()

print(f"\n=== FILTERING SUMMARY ===")
print(f"Original articles: {len(df)}")
print(f"After section filtering: {len(df_filtered)}")
print(f"Removed: {len(df) - len(df_filtered)} ({(len(df) - len(df_filtered))/len(df)*100:.2f}%)")

# Show remaining section distribution
print("\n=== REMAINING SECTIONS ===")
print(df_filtered['section'].value_counts())

=== FILTERING SUMMARY ===
Original articles: 299609
After section filtering: 209136
Removed: 90473 (30.20%)

=== REMAINING SECTIONS ===
section
New York          69610
Business Day      56914
Environment       55215
Technology        11990
U.S.               4376
World              2852
Your Money         2775
Real Estate        1422
Job Market         1098
The Upshot          838
Health              816
Automobiles         371
Science             363
Climate             253
Smarter Living      203
Washington           40
Name: count, dtype: int64

In [9]:
# Filter data from published_date >= 2008-01-01
df_filtered['published_date'] = pd.to_datetime(df_filtered['published_date'], errors='coerce')
df_filtered = df_filtered[df_filtered['published_date'] >= '2008-01-01']

In [10]:
# Save the included articles, create article_id from the index and save to a new CSV file
df_filtered['article_id'] = df_filtered.index
df_filtered.to_csv('data/01_preprocessed/articles_cleaned_sections_from_2008.csv', index=False)

In [11]:
df_filtered

,title,summary,section,keywords,published_date,url,article_id
99430,"Bloomberg in ’08? If So, Paper Chase Starts Soon",Money could smooth the way toward getting on t...,New York,"['Bloomberg, Michael R', 'Presidential Electio...",2008-01-01 05:00:00+00:00,https://www.nytimes.com/2008/01/01/nyregion/01...,99430
99431,"Boy’s Brother, 16, Believes Bullet Was Meant f...",The 11-year-old Queens boy who was shot in the...,New York,"['Crime and Criminals', 'Queens (NYC)']",2008-01-01 05:00:00+00:00,https://www.nytimes.com/2008/01/01/nyregion/01...,99431
99432,Corzine to Tour State for Plan to Cut Debt Wit...,Gov. Jon S. Corzine is going on a campaign-sty...,New York,"['Tolls', 'Roads and Traffic', 'Corzine, Jon S...",2008-01-01 05:00:00+00:00,https://www.nytimes.com/2008/01/01/nyregion/01...,99432
99433,"Gunshot Wounds Girl, 3",A 3-year-old girl was grazed by a bullet as sh...,New York,"['Crime and Criminals', 'Bronx (NYC)']",2008-01-01 05:00:00+00:00,https://www.nytimes.com/2008/01/01/nyregion/01...,99433
99434,"Edward Brennan, Who Led Sears at Its Peak, Die...",Mr. Brennan became chief executive at Sears in...,Business Day,"['Brennan, Edward', 'RETAIL STORES AND TRADE']",2008-01-01 05:00:00+00:00,https://www.nytimes.com/2008/01/01/business/01...,99434
...,...,...,...,...,...,...,...
299604,Environmental groups demand EPA to start monit...,A new legal petition filed by more than 170 to...,Environment,"['US Environmental Protection Agency', 'Plasti...",2024-12-01 13:00:07+00:00,https://www.theguardian.com/environment/2024/d...,299604
299605,"Land degradation expanding by 1m sq km a year,...",Land degradation is expanding worldwide at the...,Environment,"['Desertification', 'Farming', 'Deforestation'...",2024-12-01 12:00:07+00:00,https://www.theguardian.com/environment/2024/d...,299605
299606,"‘If I’m sent to Japan, I’m not coming home’: j...",The humpback whales watched by Paul Watson fro...,Environment,"['Sea Shepherd Conservation Society', 'Whales'...",2024-12-01 08:00:01+00:00,https://www.theguardian.com/environment/2024/d...,299606
299607,Cheaper loans on table to urge UK motorists to...,There is “no route to net zero” that ignores t...,Environment,"['Electric, hybrid and low-emission cars', 'Au...",2024-12-01 07:00:50+00:00,https://www.theguardian.com/environment/2024/d...,299607
299608,People are angry about the floods – but turnin...,There is an irony to the fact that many Welsh ...,Environment,"['Climate crisis', 'Flooding', 'Extreme weathe...",2024-12-01 06:00:48+00:00,https://www.theguardian.com/environment/2024/d...,299608

## Text repetitions

In [12]:
# Check the specific problematic articles
problematic_ids = [177755, 207059, 172718, 171579, 244118]

print("=== ANALYZING SPECIFIC PROBLEMATIC ARTICLES ===\n")

for article_id in problematic_ids:
    if article_id in df_filtered['article_id'].values:
        article = df_filtered[df_filtered['article_id'] == article_id].iloc[0]
        
        print(f"\n{'='*80}")
        print(f"ARTICLE ID: {article_id}")
        print(f"{'='*80}")
        print(f"Title: {article['title']}")
        print(f"\nSummary: {article['summary']}")
        print(f"\n--- Metadata ---")
        print(f"Section: {article['section']}")
        print(f"Published: {article['published_date']}")
        print(f"Title length: {len(str(article['title']))} chars")
        print(f"Summary length: {len(str(article['summary']))} chars")
        
        # Show combined text to see full repetition
        combined = str(article['title']) + ' ' + str(article['summary'])
        print(f"\n--- Combined Text (first 500 chars) ---")
        print(combined[:500])
        print("...")
        print(f"\n--- Combined Text (last 500 chars) ---")
        print(combined[-500:])
        
    else:
        print(f"\nArticle ID {article_id} not found in filtered dataset")

=== ANALYZING SPECIFIC PROBLEMATIC ARTICLES ===


================================================================================
ARTICLE ID: 177755
================================================================================
Title: Earnings From Walmart and More Big Retailers; Wall Street’s Annual Meetings

Summary: Walmart, Home Depot and Target are among the retailers posting results this week; Japan will report its G.D.P. on Wednesday; and the big Wall Street banks will hold their annual meetings with shareholders.

--- Metadata ---
Section: Business Day
Published: 2015-05-17 23:52:15+00:00
Title length: 75 chars
Summary length: 205 chars

--- Combined Text (first 500 chars) ---
Earnings From Walmart and More Big Retailers; Wall Street’s Annual Meetings Walmart, Home Depot and Target are among the retailers posting results this week; Japan will report its G.D.P. on Wednesday; and the big Wall Street banks will hold their annual meetings with shareholders.
...

--- Combined Text (last 500 chars) ---
Earnings From Walmart and More Big Retailers; Wall Street’s Annual Meetings Walmart, Home Depot and Target are among the retailers posting results this week; Japan will report its G.D.P. on Wednesday; and the big Wall Street banks will hold their annual meetings with shareholders.

================================================================================
ARTICLE ID: 207059
================================================================================
Title: In Battle With Amazon, Walmart Pushes Deeper Into Entertainment

Summary: Walmart’s foray into entertainment comes as the company seeks to expand its business beyond brick and mortar retailing and challenge Amazon.

--- Metadata ---
Section: Business Day
Published: 2018-10-11 12:12:41+00:00
Title length: 63 chars
Summary length: 140 chars

--- Combined Text (first 500 chars) ---
In Battle With Amazon, Walmart Pushes Deeper Into Entertainment Walmart’s foray into entertainment comes as the company seeks to expand its business beyond brick and mortar retailing and challenge Amazon.
...

--- Combined Text (last 500 chars) ---
In Battle With Amazon, Walmart Pushes Deeper Into Entertainment Walmart’s foray into entertainment comes as the company seeks to expand its business beyond brick and mortar retailing and challenge Amazon.

================================================================================
ARTICLE ID: 172718
================================================================================
Title: Washington Post Releases Free App for Kindle, in First Collaboration With Amazon

Summary: The ideas and preoccupations of Jeff Bezos, who bought The Post last year, have quietly reshaped the paper, including a new focus on international growth.

--- Metadata ---
Section: Business Day
Published: 2014-11-20 11:09:26+00:00
Title length: 80 chars
Summary length: 154 chars

--- Combined Text (first 500 chars) ---
Washington Post Releases Free App for Kindle, in First Collaboration With Amazon The ideas and preoccupations of Jeff Bezos, who bought The Post last year, have quietly reshaped the paper, including a new focus on international growth.
...

--- Combined Text (last 500 chars) ---
Washington Post Releases Free App for Kindle, in First Collaboration With Amazon The ideas and preoccupations of Jeff Bezos, who bought The Post last year, have quietly reshaped the paper, including a new focus on international growth.

================================================================================
ARTICLE ID: 171579
================================================================================
Title: Google Executive Chairman: Amazon Is a Lovely Place to Shop and Search

Summary: As the European Commission continues to negotiate an antitrust case regarding Google, the company’s chairman, Eric Schmidt, used a speech to talk about how strong Google’s competitors are.

--- Metadata ---
Section: Technology
Published: 2014-10-14 20:38:12+00:00
Title length: 70 chars
Summary length: 188 chars

--- Combined Text (first 500 chars) ---
Google Executive Chairman: Amazon Is a Lovely Place to Shop and Search As the European Commission continues to negotiate an antitrust case regarding Google, the company’s chairman, Eric Schmidt, used a speech to talk about how strong Google’s competitors are.
...

--- Combined Text (last 500 chars) ---
Google Executive Chairman: Amazon Is a Lovely Place to Shop and Search As the European Commission continues to negotiate an antitrust case regarding Google, the company’s chairman, Eric Schmidt, used a speech to talk about how strong Google’s competitors are.

================================================================================
ARTICLE ID: 244118
================================================================================
Title: The Midwestern Roots, and Woods, of N.B.A. Courts

Summary: Connor Sports, in the tiny mill town of Amasa, Mich., is one of the leading makers of hardwood floors for top professional and college teams.

--- Metadata ---
Section: Business Day
Published: 2024-12-04 10:03:00+00:00
Title length: 49 chars
Summary length: 141 chars

--- Combined Text (first 500 chars) ---
The Midwestern Roots, and Woods, of N.B.A. Courts Connor Sports, in the tiny mill town of Amasa, Mich., is one of the leading makers of hardwood floors for top professional and college teams.
...

--- Combined Text (last 500 chars) ---
The Midwestern Roots, and Woods, of N.B.A. Courts Connor Sports, in the tiny mill town of Amasa, Mich., is one of the leading makers of hardwood floors for top professional and college teams.

Most severe case was 177755, check.

In [13]:
# Check if the repetition is in the actual data or just in display
print("=== CHECKING RAW SUMMARY FIELD FOR ARTICLE 177755 ===\n")

article = df_filtered[df_filtered['article_id'] == 177755].iloc[0]

print(f"Title: {article['title']}")
print(f"\nRaw Summary:")
print(article['summary'])
print(f"\nSummary contains title? {article['title'] in str(article['summary'])}")

# Check for internal repetitions in summary
summary_text = str(article['summary'])
sentences = [s.strip() for s in summary_text.split(';')]
print(f"\nSummary split by semicolon:")
for i, sent in enumerate(sentences, 1):
    print(f"{i}. {sent}")

# Check if any sentence repeats
from collections import Counter
sentence_counts = Counter(sentences)
repeated = [sent for sent, count in sentence_counts.items() if count > 1]
if repeated:
    print(f"\n⚠️ Repeated sentences found:")
    for sent in repeated:
        print(f"  - {sent}")
else:
    print("\n✅ No repeated sentences in summary")

=== CHECKING RAW SUMMARY FIELD FOR ARTICLE 177755 ===

Title: Earnings From Walmart and More Big Retailers; Wall Street’s Annual Meetings

Raw Summary:
Walmart, Home Depot and Target are among the retailers posting results this week; Japan will report its G.D.P. on Wednesday; and the big Wall Street banks will hold their annual meetings with shareholders.

Summary contains title? False

Summary split by semicolon:
1. Walmart, Home Depot and Target are among the retailers posting results this week
2. Japan will report its G.D.P. on Wednesday
3. and the big Wall Street banks will hold their annual meetings with shareholders.

✅ No repeated sentences in summary

In [14]:
# Find articles with repetitions in the summary itself
print("=== FINDING ACTUAL REPETITIONS IN SUMMARY FIELD ===\n")

def has_internal_repetition(summary):
    """Check if summary has internal repetition"""
    if pd.isna(summary):
        return False, 0, None
    
    summary = str(summary)
    
    # Method 1: Check if exact half repeats
    if len(summary) > 100:
        mid = len(summary) // 2
        first_half = summary[:mid].lower().strip()
        second_half = summary[mid:].lower().strip()
        if first_half == second_half:
            return True, 100, "exact_half_duplication"
    
    # Method 2: Check for repeated sentences
    sentences = [s.strip() for s in re.split(r'[.!?;]+', summary) if len(s.strip()) > 15]
    if len(sentences) > 1:
        sentence_counts = Counter(s.lower() for s in sentences)
        max_count = max(sentence_counts.values())
        if max_count > 2:
            return True, max_count * 20, "repeated_sentences"
    
    # Method 3: Check for repeated 5-word phrases
    words = summary.split()
    if len(words) >= 10:
        phrases = [' '.join(words[i:i+5]).lower() for i in range(len(words) - 4)]
        phrase_counts = Counter(phrases)
        max_repeats = max(phrase_counts.values()) if phrases else 0
        num_repeated = sum(1 for count in phrase_counts.values() if count > 1)
        
        if max_repeats > 3 or num_repeated > 5:
            return True, max_repeats * 10 + num_repeated * 5, "repeated_phrases"
    
    return False, 0, None

# Apply to all articles
results = df_filtered['summary'].apply(has_internal_repetition)
df_filtered['has_summary_repetition'] = results.apply(lambda x: x[0])
df_filtered['repetition_score'] = results.apply(lambda x: x[1])
df_filtered['repetition_type'] = results.apply(lambda x: x[2])

articles_with_rep = df_filtered['has_summary_repetition'].sum()
print(f"Articles with internal summary repetition: {articles_with_rep} ({articles_with_rep/len(df_filtered)*100:.2f}%)")

if articles_with_rep > 0:
    print("\n=== ARTICLES WITH REPETITION ===")
    repetitive = df_filtered[df_filtered['has_summary_repetition']].nlargest(10, 'repetition_score')
    
    for idx, row in repetitive.iterrows():
        print(f"\nArticle ID: {row['article_id']}")
        print(f"Title: {row['title']}")
        print(f"Type: {row['repetition_type']}")
        print(f"Score: {row['repetition_score']}")
        print(f"Summary (first 300 chars): {str(row['summary'])[:300]}...")
        print(f"Summary (last 300 chars): ...{str(row['summary'])[-300:]}")

=== FINDING ACTUAL REPETITIONS IN SUMMARY FIELD ===

Articles with internal summary repetition: 1925 (1.42%)

=== ARTICLES WITH REPETITION ===

Article ID: 265080
Title: Rio+20 'Future we Want' draft text - exclusive copy of the document
Type: repeated_phrases
Score: 4190
Summary (first 300 chars): Our Common Vision 1. We, the heads of State and Government and high level representatives, having met at Rio de Janeiro, Brazil, from 20-22 June 2012, with full participation of civil society, renew our commitment to sustainable development, and to ensure the promotion of economically, socially and ...
Summary (last 300 chars): ...he Secretary-General to compile these commitments and facilitate access to other registries that have compiled commitments, in an internet-based registry. The registry should make information about the commitments fully transparent and accessible to the public, and it should be periodically updated.

Article ID: 293355
Title: First draft of Cop27 text: what it says and what it means
Type: repeated_phrases
Score: 1730
Summary (first 300 chars): The first thing to be said about this early draft of a potential cover decision for the Cop27 UN climate summit in Egypt, now entering its final days, is that it is a monster. Coming in at 20 pages, it seems to include text on everything from cutting greenhouse gas emissions (mitigation, in the UN j...
Summary (last 300 chars): ...in sight. A final settlement of loss and damage was always unlikely at these talks, but the fact that countries are now talking about it in a detailed way is a step forward. If progress can be made on the key issue of World Bank reform outside these talks, it would open up far greater possibilities.

Article ID: 274183
Title: Government’s energy policies are just blowing in the wind
Type: repeated_phrases
Score: 1460
Summary (first 300 chars): Huw Rowlands (Letters) goes too far when he says: “Anyone who has researched the fracking industry is against it.” His assertion ignores a large body of research into fracking that has been and continues to be undertaken by the geological community, including the Earth sciences departments of severa...
Summary (last 300 chars): ...Professor in Politics and International Studies, University of Warwick Dr Cosimo Zene, Reader in the Study of Religions, SOAS, University of London Dr Diego Acosta Arcarazo Senior Lecturer in European and Migration Law University of Bristol. Dr Nick Vivyan, Lecturer in Politics, University of Durham

Article ID: 259825
Title: 'Climategate' report - live blog
Type: repeated_phrases
Score: 1365
Summary (first 300 chars): 9.53am: Morning all. Today's the big day for "climategate", with the publication of the largest and final report on the controversy surrounding the emails leaked or stolen – no one knows – from the University of East Anglia's Climatic Research Unit. The report itself will be released at 1pm UK time,...
Summary (last 300 chars): ...t, but that's it from me. Thanks for all the comments. Lastly, you can join a live Guardian debate on 'Climategate' with a stellar panel in London, on 14 July. It's being chaired by George Monbiot and will have Prof Bob Watson, Fred Pearce, Steve McIntyre and other special guests. More details here.

Article ID: 273614
Title: Exxon knew of climate change in 1981, email says – but it funded deniers for 27 more years
Type: repeated_phrases
Score: 1210
Summary (first 300 chars): ExxonMobil, the world’s biggest oil company, knew as early as 1981 of climate change – seven years before it became a public issue, according to a newly discovered email from one of the firm’s own scientists. Despite this the firm spent millions over the next 27 years to promote climate denial. The ...
Summary (last 300 chars): ...hat they are trying to minimize their internal CO2 emissions. Mostly, they are doing this by improving energy efficiency and reducing cost. The same is true for internal recycling, again a practice most companies follow. Its [sic] just good engineering. I could go on, but this e-mail is long enough.

Article ID: 263124
Title: Glencore on its safety record, environmental performance and tax
Type: repeated_phrases
Score: 865
Summary (first 300 chars): One of the business stories of the year so far was the flotation in May of Glencore, the global commodities trader. Not only did the flotation shine a light on "the biggest company you've never heard of", as some described the secretive, Switzerland-based private firm, but it also revealed the extra...
Summary (last 300 chars): ...his area and in close collaboration with the Colombian authorities and of course the affected communities. The companies are still investigating the possible effects and consulting with local communities to reach a common consensus. This will establish the appropriate processes for the resettlement.

Article ID: 262489
Title: Transcript of an interview with Jeffrey Gleason
Type: repeated_sentences
Score: 840
Summary (first 300 chars): January 20, 2011 ERIC MAY: It is January 20, 2011. This is Special Agent Eric May with the Department of Interior, Office of Inspector General. I'm accompanied by Special Agent John Meskel with the Department of Interior, Office of Inspector General, and we're with Jeffrey Gleason. Jeff, do you cons...
Summary (last 300 chars): ... in here with anybody, particularly Mr. Monnett, you know, talking with us, because it is an ongoing investigation, okay? JEFFREY GLEASON: Okay. And if I might ask, "investigating"? ERIC MAY: The validity of the paper and the photos. Nothing? All right, that concludes our interview. It is now 12:42.

Article ID: 293330
Title: Second draft of Cop27 text: what has changed since the first draft?
Type: repeated_phrases
Score: 790
Summary (first 300 chars): At 10 pages, this second draft of the Cop27 cover text is just half the length of the previous version, which will come as a relief to negotiators. Many of the ramblings and repetitions of the previous version have been removed or tidied up, but some key points have been weakened or left out. There ...
Summary (last 300 chars): ...sidency and the UN high-level champions, in collaboration with the UN Regional Economic Commissions, on climate initiatives to finance climate action and the SDGs. Was there pressure to bring the document down to less than 100 paragraphs? It is still a long text, and further editing can be expected.

Article ID: 255903
Title: The Aga saga: George Monbiot v William McGrath
Type: repeated_phrases
Score: 765
Summary (first 300 chars): MONBIOT: I'm George Monbiot and I'm talking to William McGrath who's the chief executive of Aga Rangemaster who's kindly come in to talk about Aga's environmental performance. And we've had a bit of a spat about this in the paper where I wrote a paragraph or two expressing my displeasure with Aga's ...
Summary (last 300 chars): ...ry much attune to the over all green agenda. And I think, I think you're somebody that we would like to see actually coming on board. Because we do see that we're, we are exactly, we think we are the kind of company that people like yourself should be rooting for, not attacking ... END OF TRANSCRIPT

Article ID: 263797
Title: The government must embrace a green future
Type: repeated_phrases
Score: 740
Summary (first 300 chars): The environmental movement has spoken out repeatedly against policies that put short-term profit ahead of our countryside and wildlife, eroding our natural capital and quality of life, but rarely have we been as incredulous as we were last Tuesday, hearing the autumn statement. The stunning disregar...
Summary (last 300 chars): ...e's stone genitals were found years later when the gatekeeper to Père Lachaise cemetery died ("Sealed without a kiss: Oscar Wilde's lipstick-covered tomb protected", News). His office was being cleared out when it was discovered he had been using them as a paperweight. Spencer Butler Bridport Dorset

In [15]:
# Analyze the types of repetitive articles more carefully
print("=== ANALYZING REPETITIVE ARTICLES ===\n")

# Look at sections of repetitive articles
print("Sections with most repetitions:")
repetitive_sections = df_filtered[df_filtered['has_summary_repetition']]['section'].value_counts()
print(repetitive_sections)

# Check if these are specific types of content
print("\n=== Examples by Type ===")

# Check for transcripts (like article 262489)
df_filtered['is_transcript'] = df_filtered['title'].str.contains('transcript|interview', case=False, na=False)

# Check for live blogs (like article 259825)
df_filtered['is_liveblog'] = df_filtered['title'].str.contains('live blog|live coverage', case=False, na=False) | \
                              df_filtered['summary'].str.contains('live blog|live coverage', case=False, na=False)

# Check for documents/drafts (like articles 265080, 293355, 293330)
df_filtered['is_document'] = df_filtered['title'].str.contains('draft|document|text|report', case=False, na=False)

# Check for letters/opinion collections (like article 274183)
df_filtered['is_letters'] = df_filtered['title'].str.contains('letter|letters to the editor', case=False, na=False)

print("\nBreakdown of repetitive articles:")
repetitive = df_filtered[df_filtered['has_summary_repetition']]
print(f"- Transcripts: {repetitive['is_transcript'].sum()}")
print(f"- Live blogs: {repetitive['is_liveblog'].sum()}")
print(f"- Documents/drafts: {repetitive['is_document'].sum()}")
print(f"- Letters: {repetitive['is_letters'].sum()}")
print(f"- Other: {len(repetitive) - (repetitive['is_transcript'].sum() + repetitive['is_liveblog'].sum() + repetitive['is_document'].sum() + repetitive['is_letters'].sum())}")

=== ANALYZING REPETITIVE ARTICLES ===

Sections with most repetitions:
section
Environment    1925
Name: count, dtype: int64

=== Examples by Type ===

Breakdown of repetitive articles:
- Transcripts: 3
- Live blogs: 12
- Documents/drafts: 66
- Letters: 6
- Other: 1838

In [16]:
# Review different severity levels
print("\n=== REPETITION SEVERITY ANALYSIS ===\n")

# Distribution by score
print("Repetition score distribution:")
print(df_filtered[df_filtered['has_summary_repetition']]['repetition_score'].describe())

# Show different severity buckets
severe = df_filtered[df_filtered['repetition_score'] > 1000]
moderate = df_filtered[(df_filtered['repetition_score'] > 500) & (df_filtered['repetition_score'] <= 1000)]
mild = df_filtered[(df_filtered['repetition_score'] > 0) & (df_filtered['repetition_score'] <= 500)]

print(f"\nSevere (score > 1000): {len(severe)} articles ({len(severe)/len(df_filtered)*100:.2f}%)")
print(f"Moderate (500 < score <= 1000): {len(moderate)} articles ({len(moderate)/len(df_filtered)*100:.2f}%)")
print(f"Mild (0 < score <= 500): {len(mild)} articles ({len(mild)/len(df_filtered)*100:.2f}%)")

# Sample from each category
print("\n=== SEVERE EXAMPLES ===")
for idx, row in severe.iterrows():
    print(f"\nArticle ID: {row['article_id']}")
    print(f"Title: {row['title']}")
    print(f"Score: {row['repetition_score']}")
    print(f"Type: Transcript={row['is_transcript']}, LiveBlog={row['is_liveblog']}, Document={row['is_document']}")

print("\n=== MODERATE EXAMPLES ===")
for idx, row in moderate.head(3).iterrows():
    print(f"\nArticle ID: {row['article_id']}")
    print(f"Title: {row['title']}")
    print(f"Score: {row['repetition_score']}")
    print(f"Type: Transcript={row['is_transcript']}, LiveBlog={row['is_liveblog']}, Document={row['is_document']}")

=== REPETITION SEVERITY ANALYSIS ===

Repetition score distribution:
count    1925.000000
mean       90.389610
std       132.112332
min        45.000000
25%        55.000000
50%        65.000000
75%        90.000000
max      4190.000000
Name: repetition_score, dtype: float64

Severe (score > 1000): 5 articles (0.00%)
Moderate (500 < score <= 1000): 12 articles (0.01%)
Mild (0 < score <= 500): 1908 articles (1.40%)

=== SEVERE EXAMPLES ===

Article ID: 259825
Title: 'Climategate' report - live blog
Score: 1365
Type: Transcript=False, LiveBlog=True, Document=True

Article ID: 265080
Title: Rio+20 'Future we Want' draft text - exclusive copy of the document
Score: 4190
Type: Transcript=False, LiveBlog=False, Document=True

Article ID: 273614
Title: Exxon knew of climate change in 1981, email says – but it funded deniers for 27 more years
Score: 1210
Type: Transcript=False, LiveBlog=False, Document=False

Article ID: 274183
Title: Government’s energy policies are just blowing in the wind
Score: 1460
Type: Transcript=False, LiveBlog=False, Document=False

Article ID: 293355
Title: First draft of Cop27 text: what it says and what it means
Score: 1730
Type: Transcript=False, LiveBlog=False, Document=True

=== MODERATE EXAMPLES ===

Article ID: 255903
Title: The Aga saga: George Monbiot v William McGrath
Score: 765
Type: Transcript=False, LiveBlog=False, Document=False

Article ID: 260304
Title: BP oil spill report – as it happened
Score: 510
Type: Transcript=False, LiveBlog=False, Document=True

Article ID: 260940
Title: Cancún climate change summit: The final day as it happened
Score: 505
Type: Transcript=False, LiveBlog=True, Document=False

Seem like repetitve data is not an issue in raw data, check later preprocessing step (especially when we merge title and summary). => no action here needed.

In [17]:
# Clean up repetition analysis columns first
temp_cols = ['has_summary_repetition', 'repetition_score', 'repetition_type', 
             'is_transcript', 'is_liveblog', 'is_document', 'is_letters']
df_filtered = df_filtered.drop(columns=[c for c in temp_cols if c in df_filtered.columns], errors='ignore')

## Other issues with long articles

In [18]:
# Check the problematic articles from previous test set
problematic_long_ids = [253898, 296646, 253767]

print("=== ANALYZING PROBLEMATIC LONG ARTICLES ===\n")

for article_id in problematic_long_ids:
    if article_id in df_filtered['article_id'].values:
        article = df_filtered[df_filtered['article_id'] == article_id].iloc[0]
        
        print(f"\n{'='*80}")
        print(f"ARTICLE ID: {article_id}")
        print(f"{'='*80}")
        print(f"Title: {article['title']}")
        print(f"Section: {article['section']}")
        print(f"Published: {article['published_date']}")
        print(f"\nTitle length: {len(str(article['title']))} chars")
        print(f"Summary length: {len(str(article['summary']))} chars")
        print(f"Total length: {len(str(article['title'])) + len(str(article['summary']))} chars")
        
        print(f"\n--- Title ---")
        print(article['title'])
        
        print(f"\n--- Summary (first 500 chars) ---")
        print(str(article['summary'])[:500])
        print("...")
        
        print(f"\n--- Summary (last 500 chars) ---")
        print("...")
        print(str(article['summary'])[-500:])
        
    else:
        print(f"\nArticle ID {article_id} not found in filtered dataset")

=== ANALYZING PROBLEMATIC LONG ARTICLES ===


================================================================================
ARTICLE ID: 253898
================================================================================
Title: Greenwatch: China closes Everest for clean-up
Section: Environment
Published: 2008-07-01 08:57:27+00:00

Title length: 45 chars
Summary length: 1738 chars
Total length: 1783 chars

--- Title ---
Greenwatch: China closes Everest for clean-up

--- Summary (first 500 chars) ---
China closes Everest for clean-up >>Source: The Independent China is planning to restrict access by climbers to the summit of Mount Everest - known in China as Mount Qomolangma - to allow environmental teams to carry out a huge clean-up of the world's highest rubbish dump. Can a cow hormone help save the environment? >>Source: New Scientist Does a much-maligned product from Monsanto, have hidden environmental benefits? An analysis of the bovine hormone somatotropin, which is given to cows to boo
...

--- Summary (last 500 chars) ---
...
ist White House officials refused to open e-mail from the US environmental protection agency that said global warming threatens public welfare and urged more fuel-efficient cars, congressional staff said. French to reconsider EU biofuel goal >>Source: Treehugger French secretary of state for ecology Nathalie Kosciusko-Morizet says that setting a specific quota for biofuels was probably a mistake and the emphasis should instead be on setting strict environmental and social criteria for their use.

================================================================================
ARTICLE ID: 296646
================================================================================
Title: World will look back at 2023 as year humanity exposed its inability to tackle climate crisis, scientists say
Section: Environment
Published: 2023-12-29 14:26:31+00:00

Title length: 108 chars
Summary length: 8738 chars
Total length: 8846 chars

--- Title ---
World will look back at 2023 as year humanity exposed its inability to tackle climate crisis, scientists say

--- Summary (first 500 chars) ---
The hottest year in recorded history casts doubts on humanity’s ability to deal with a climate crisis of its own making, senior scientists have said. As historically high temperatures continued to be registered in many parts of the world in late December, the former Nasa scientist James Hansen told the Guardian that 2023 would be remembered as the moment when failures became apparent. “When our children and grandchildren look back at the history of human-made climate change, this year and next w
...

--- Summary (last 500 chars) ---
...
y” and catastrophes of 2023 would first become the new norm, and then be looked back on as one of the cooler, more stable years in people’s lives. As Hansen warned, unless there is radical and rapid change, failure will be built into the climate system. • This article was amended on 1 January 2024. Owing to an error in the editing process an earlier version referred to the wildfire in Lahaina on Maui island as the “deadliest in US history”. That should have said “deadliest in recent US history”.

================================================================================
ARTICLE ID: 253767
================================================================================
Title: Greenwatch: Climate change deaths report 'buried'
Section: Environment
Published: 2008-07-16 09:17:05+00:00

Title length: 49 chars
Summary length: 1506 chars
Total length: 1555 chars

--- Title ---
Greenwatch: Climate change deaths report 'buried'

--- Summary (first 500 chars) ---
US: White House buries climate change deaths report >> Source: Telegraph The White House buried a report prepared by US government scientists which detailed a rising death toll from heat waves, fires, disease and smog they predicted would be caused by global warming. US floods to create record 'dead zone' >> Source: New Scientist Chemicals in runoff following the devastating floods in the American Midwest this summer are having a knock-on effect on marine life many miles away. Australia: Protest
...

--- Summary (last 500 chars) ---
...
rce: Independent Smythson, the Queen's stationer which employs the wife of the Conservative leader, David Cameron, as its creative director, is selling luxury gifts bound with the skins of rare lizards. EU executive to tackle eco impact of consumerism >> Source: ENN The European commission is to launch a raft of proposals today to curb the environmental impact of consumerism in the 27-nation EU by supporting ecofriendly products and technology. Spotted a good story online? Share your links below

In [19]:
# Analyze article length distribution
print("\n=== ANALYZING ARTICLE LENGTH DISTRIBUTION ===\n")

df_filtered['title_length'] = df_filtered['title'].fillna('').astype(str).str.len()
df_filtered['summary_length'] = df_filtered['summary'].fillna('').astype(str).str.len()
df_filtered['total_length'] = df_filtered['title_length'] + df_filtered['summary_length']

print("Length statistics:")
print(df_filtered[['title_length', 'summary_length', 'total_length']].describe())

print("\nPercentiles:")
for p in [50, 75, 90, 95, 99, 99.5]:
    val = df_filtered['total_length'].quantile(p/100)
    print(f"  {p}th percentile: {val:.0f} characters")

# Check where our problematic articles fall
print("\n=== PROBLEMATIC ARTICLES IN DISTRIBUTION ===")
for article_id in problematic_long_ids:
    if article_id in df_filtered['article_id'].values:
        length = df_filtered[df_filtered['article_id'] == article_id]['total_length'].values[0]
        percentile = (df_filtered['total_length'] < length).sum() / len(df_filtered) * 100
        print(f"Article {article_id}: {length} chars (top {100-percentile:.1f}%)")

=== ANALYZING ARTICLE LENGTH DISTRIBUTION ===

Length statistics:
        title_length  summary_length   total_length
count  135962.000000   135962.000000  135962.000000
mean       54.728233     1574.254468    1628.982701
std        16.095573     2632.539196    2637.594114
min         3.000000        1.000000      18.000000
25%        44.000000      134.000000     185.000000
50%        55.000000      161.000000     217.000000
75%        66.000000     2603.000000    2661.000000
max       213.000000   169092.000000  169159.000000

Percentiles:
  50th percentile: 217 characters
  75th percentile: 2661 characters
  90th percentile: 4970 characters
  95th percentile: 6307 characters
  99th percentile: 10745 characters
  99.5th percentile: 13394 characters

=== PROBLEMATIC ARTICLES IN DISTRIBUTION ===
Article 253898: 1783 chars (top 32.0%)
Article 296646: 8846 chars (top 1.8%)
Article 253767: 1555 chars (top 33.0%)

In [20]:
# Show examples at different length ranges
print("\n=== EXAMPLES AT DIFFERENT LENGTH RANGES ===\n")

length_ranges = [
    (0, 500, "Very short"),
    (500, 1000, "Short (typical)"),
    (1000, 1500, "Medium"),
    (1500, 2500, "Long"),
    (2500, 4000, "Very long"),
    (4000, 100000, "Extremely long")
]

for min_len, max_len, label in length_ranges:
    articles_in_range = df_filtered[
        (df_filtered['total_length'] >= min_len) & 
        (df_filtered['total_length'] < max_len)
    ]
    
    print(f"\n{'='*80}")
    print(f"{label} ({min_len}-{max_len} chars): {len(articles_in_range)} articles ({len(articles_in_range)/len(df_filtered)*100:.2f}%)")
    print('='*80)
    
    if len(articles_in_range) > 0:
        # Sample 3 random articles
        sample = articles_in_range.sample(min(3, len(articles_in_range)))
        for idx, row in sample.iterrows():
            print(f"\nArticle ID: {row['article_id']} | Length: {row['total_length']}")
            print(f"Title: {row['title'][:90]}...")
            print(f"Summary preview: {str(row['summary'])[:150]}...")

=== EXAMPLES AT DIFFERENT LENGTH RANGES ===


================================================================================
Very short (0-500 chars): 88369 articles (65.00%)
================================================================================

Article ID: 109922 | Length: 159
Title: Not Everyone Is Cheering as Wi-Fi Takes to the Air...
Summary preview: Wireless Internet service on airlines may become a new source of tension between passengers on packed planes....

Article ID: 167003 | Length: 182
Title: Hotels Embrace the Campus Nearby...
Summary preview: Large chains are increasingly joining established independent hotels by tailoring their decorations and amenities to attract college-related business....

Article ID: 142029 | Length: 255
Title: Fourth-Quarter Profit and Revenue Declined at The New York Times Company...
Summary preview: Fourth-quarter profit declined as rising subscription and digital advertising revenue at the company’s largest newspapers could not offset the continu...

================================================================================
Short (typical) (500-1000 chars): 783 articles (0.58%)
================================================================================

Article ID: 283288 | Length: 993
Title: Plastic technology for natural recycling...
Summary preview: Your article (Plastic plague: tiny particles can reach anywhere on the planet, say scientists, 16 April) says that “about 335m tonnes of plastic is pr...

Article ID: 252070 | Length: 765
Title: Cancer drugs at risk as plant species die off...
Summary preview: Medicines for HIV and cancer could be lost because plants used in their preparation are facing extinction, experts have warned. Deforestation and over...

Article ID: 266421 | Length: 960
Title: Windfarm support...
Summary preview: While windfarms are certainly a matter of contention within the government, this is not a reflection of the nation at large (Windfarms: the bitter fig...

================================================================================
Medium (1000-1500 chars): 1692 articles (1.24%)
================================================================================

Article ID: 267085 | Length: 1370
Title: Hartlepool nuclear power plant fire triggers emergency response...
Summary preview: A fire at a nuclear power plant triggered a major response by emergency services after smoke was seen billowing into the air. Police and fire crews we...

Article ID: 280481 | Length: 1212
Title: Ozone layer, farm antibiotics and mutant crayfish – green news roundup...
Summary preview: Environment news Revealed: Trudeau government welcomed oil lobby help for US pipeline push EPA head Scott Pruitt says global warming may help ‘humans ...

Article ID: 277805 | Length: 1121
Title: How electric car drivers are being overcharged...
Summary preview: As a relatively new owner of a Nissan Leaf, I support entirely the need for adequate provision of charge points (Letters, 29 November). The ecotricity...

================================================================================
Long (1500-2500 chars): 9869 articles (7.26%)
================================================================================

Article ID: 252478 | Length: 1748
Title: Country diary...
Summary preview: My route for the daily walk with two of the dachshunds has changed and it means we turn back at the river bridge. It is what I would call a narrow, hu...

Article ID: 264923 | Length: 2063
Title: Skies may be grey, but dextrous swallows show that spring is here...
Summary preview: The leaden sky is depressing, toning down the vibrant greens of the young growth bursting out from shrub and tree. Ibsley Water offers a palette of gr...

Article ID: 281645 | Length: 2003
Title: Wasp traps increase the risk of stings...
Summary preview: The article about wasps by Ben Aldiss (Keep calm and wear white…, theguardian.com, 24 August) was very helpful in explaining why calm behaviour, remov...

================================================================================
Very long (2500-4000 chars): 13417 articles (9.87%)
================================================================================

Article ID: 256863 | Length: 3161
Title: Al Gore reaches 1 million Twitter followers...
Summary preview: Yesterday afternoon Al Gore achieved another landmark in his career as a politician and environmental campaigner as he clocked up his millionth follow...

Article ID: 272164 | Length: 3423
Title: Cameron's climate envoy blames big six energy firms for green deal's failure...
Summary preview: The big six energy companies undermined the government’s flagship programme to upgrade the energy efficiency of Britain’s housing stock, according to ...

Article ID: 264885 | Length: 3953
Title: Don't dismiss geoengineering – we may need it one day...
Summary preview: Opponents of geoengineering will no doubt seize upon this week's cancellation of the fieldwork element of the Spice project as a significant victory i...

================================================================================
Extremely long (4000-100000 chars): 21830 articles (16.06%)
================================================================================

Article ID: 257356 | Length: 9241
Title: Do we really need to ban plastic bags?...
Summary preview: Massing in their millions, crucified and shredded on barbed wire fences, plastic bags have come to be dubbed "roadside daisies" in South Africa. Some ...

Article ID: 290146 | Length: 5598
Title: UK will press governments to stick to climate pledges, says Cop26 president...
Summary preview: The UK will continue to press governments around the world to cut greenhouse gas emissions urgently in the next year to limit global heating to 1.5C, ...

Article ID: 278440 | Length: 7435
Title: Renewables roadshow: how the people of Newtown got behind solar-powered beer...
Summary preview: Newtown – Sydney’s grungy inner-city suburb where a seemingly endless string of Thai restaurants is interrupted by body-piercing shops, clothes stores...

Since there are many long articles, we continue with linking entities to naturally filter out irrelevant articles, and then consider the long articles later.

# Final Data Check

In [21]:
df_date = df.copy()
df_date['published_date'] = pd.to_datetime(
    df_date['published_date'], errors='coerce'
)

df_date = df_date[
    df_date['published_date'] >= '2008-01-01'
]

print("After date restriction:", len(df_date))

df_date_section = df_date[
    df_date['section'].isin(INCLUDE_SECTIONS) &
    df_date['section'].notna()
]

print("After date + section restriction:", len(df_date_section))

After date restriction: 192602
After date + section restriction: 135962